#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa xxxaaabbbcccxxx aws-key
  - name: tbz
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
ssh_pwauth: false #Erlaubt den Usern die Verbindung mit einem Passwort über SSH zu machen. Falls false nur Public/Private Key Methode wäre erlaubt
disable_root: false # Login als Root User über SSH ist erlaubt
package_update: true
timezone: EU/Central
locale: de_CH
packages: #Packages die auf der Machine installiert werden sollten
  - curl
  - wget
