#cloud-config
users:
  - name: ubuntu #User name
    sudo: ALL=(ALL) NOPASSWD:ALL #SUDO Rules
    groups: users, admin # Benutzergruppen, zu denen der Benutzer gehört
    home: /home/ubuntu #Pfad zum Home verzeichnis. Wenn der User "cd ~" ausführt geht er zu diesem Pfad
    shell: /bin/bash #Definiert dass Bash als Shell verwendet werden sollte.
    lock_passwd: false #Erlaubt den Usern ihre Passwörter zu ändern
    plain_text_passwd: "password" # Default password (nicht Hashed)
ssh_pwauth: true #Erlaubt den Usern die Verbindung mit einem Passwort über SSH zu machen. Falls false nur Public/Private Key Methode wäre erlaubt
disable_root: false # Login als Root User über SSH ist erlaubt
packages: #Packages die auf der Machine installiert werden sollten
  - apache2
  - curl
  - wget
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
write_files:
  - path: /var/www/html/db.php
    content: |
      <?php
          //database
          $servername = "172.26.6.250";
          $username = "admin";
          $password = "password";
          $dbname = "mysql";

          // Create connection
          $conn = new mysqli($servername, $username, $password, $dbname);
          // Check connection
          if ($conn->connect_error) {
                  die("Connection failed: " . $conn->connect_error);
          }

          $sql = "select Host, User from mysql.user;";
          $result = $conn->query($sql);
          while($row = $result->fetch_assoc()){
                  echo($row["Host"] . " / " . $row["User"] . "<br />");
          }
          //var_dump($result);
      ?>
  - path: /var/www/html/info.php
    content: |
      <?php

      // Show all information, defaults to INFO_ALL
      phpinfo();

      ?>
