#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCF3E1UzKDMUiT06rqiRuGlvqZy/YTCQhtAPoMcz3UsAlrtMTlGxjABcPT2JfoO6EbIVf2zoYgyZtrPGPjSSzUonDEyvn+zGNsQD5S9v2KZp5q9vtqOBMLepSgXF6vWyaVn0A7Wn5Kp0fBA5ja8sZ1OkAEMBlK00Ob8p9uLR98Sdwp78tjkmL3EBNedlNfGI3TatTMUBL0O4FytSKtQncOqFPrg9OcXsawK2smTYNfVADz3agjk+27pXdYhU/7L6g7XWynCa/U1sfK8mu/cfBHpYLQTjVTMHZKcUR01und+AVAA0BCgYhfnK1yHwCaFlvDOWACHQK4zFxMAL7uu5eL3 aws-key
ssh_pwauth: false #Erlaubt den Usern die Verbindung mit einem Passwort über SSH zu machen. Falls false nur Public/Private Key Methode wäre erlaubt
disable_root: false # Login als Root User über SSH ist erlaubt
package_update: true
packages: #Packages die auf der Machine installiert werden sollten
  - mariadb-server
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service
